### ISSUE TITLE
assertThrown should not break debugging

### ISSUE THREAD

**Issue by vporton** [BBasile/dexed#394]
It is rectifies #393. I decided to open a separate issue because now I know much more details.

I compile the following program in `unittest` mode:

```
import std.typecons;
import std.stdio;

void main() {
    auto i = Nullable!int(1);
    writeln("Test run.");
}
```

Then I set a breakpoint in `writeln` line and start debugging.

Howmany I click "Continue", control never reaches `main()`, making it impossible to debug.

The control is stalled at `std.typecons`, line 2864:

```
assertThrown!AssertError(i = ni);
```

Dexed 3.7.0.

LDC 1.11.0

**Comment by vporton** [comment]
Note that debugging with DDD 3.3.12 (x86_64-pc-linux-gnu) program does work.

So, it is a problem with Dexed not with GDB itself.

**Comment by vporton** [comment]
Phobos 1.11.0-2

**Comment by BBasile** [comment]
DDD does not even break by itself  for

```d
#!dmd -g
module runnable;
void main()
{
    throw new Exception("");
}         
```

This is because it does not know that D uses `_d_throwdwarf` and this special symbol was added a couple of years ago while DDD last update year is over 5 years. I'm not even sure if it break with the previous one (i dont remember its name maybe it was `_d_throwc` but i'm 99% sure that DDD didn't auto break either.)

GDB commander catches absolutely all `Throwable` and `assertThrown` is supposed to throw so things are happen exactly as they are supposed to. So not a bug but possible enhancement.

**Comment by vporton** [comment]
Whether it is a bug or an enhancement, it *forces* me to debug using DDD not Dexed builtin debugger. It is definitely not good.

**Comment by BBasile** [comment]
Ok. I've decided to put an option that will cancel all the default breakpoints Dexed set [by default](https://github.com/BBasile/dexed/blob/fee4a1b0d168f9d9af92f51dcd53fd27cc08490a/src/u_gdb.pas#L1813-L1834).

**Comment by BBasile** [comment]
In 3.7.1 you'll be able to deactivate the d specific breakpoints.

![gdb_com_def_syms-2](https://user-images.githubusercontent.com/16154339/51098344-ef2bc800-17c9-11e9-8904-159a7ceb5751.png)
